### ISSUE TITLE
Need help in reproducing the results

### ISSUE THREAD

**Issue by saikatdutta** [caoql98/OVRS#3]
Hi, 

Thank you for this interesting work. We wanted to reproduce the results, but we are unable to match the results reported in the paper. We used iSAID as training dataset. First, we tried with `cat_seg/cat_seg_model_ours.py ` and `cat_seg/modeling/transformer/model_ours.py` and got the following results:

ISAID val: 83.60
DLRSD: 22.58
Potsdam: 15.4
Vaihingen: 13.4

Next, we noticed SAU module was not present in `cat_seg/modeling/transformer/model_ours.py`, so we integrated necessary changes from `cat_seg/modeling/transformer/model_attention.py` file. This yields the following results:

ISAID val: 81.44
DLRSD: 23.33 
Potsdam: 15.40
Vaihingen: 14.98

These models are trained for 100K iterations. Is there any other change that we need to do for reproducing the results?

Thanks in advance.

**Comment by caoql98** [comment]
hi，do you have an email so that I will send you with my log.txt

**Comment by derektan95** [comment]
Hi @saikatdutta, 

I am trying to evaluate the model as well. Did you encounter this issue when evaluating the model with iSAID? It was training fine until I encountered this error. 

Hi @caoql98 do you have any insights on this? Thanks!

```
[12/16 17:10:38 d2.utils.events]:  eta: 12:55:10  iter: 4879  total_loss: 0.001177    time: 0.6196  last_time: 0.6171  data_time: 0.0036  last_data_time: 0.0018   lr: 0.00019817  max_mem: 19774M
[12/16 17:10:51 d2.utils.events]:  eta: 12:55:11  iter: 4899  total_loss: 0.000974    time: 0.6196  last_time: 0.6297  data_time: 0.0045  last_data_time: 0.0100   lr: 0.00019816  max_mem: 19774M
[12/16 17:11:03 d2.utils.events]:  eta: 12:54:59  iter: 4919  total_loss: 0.001061    time: 0.6196  last_time: 0.6238  data_time: 0.0025  last_data_time: 0.0017   lr: 0.00019814  max_mem: 19774M
[12/16 17:11:15 d2.utils.events]:  eta: 12:54:46  iter: 4939  total_loss: 0.0008647    time: 0.6196  last_time: 0.6206  data_time: 0.0029  last_data_time: 0.0016   lr: 0.00019812  max_mem: 19774M
[12/16 17:11:28 d2.utils.events]:  eta: 12:54:13  iter: 4959  total_loss: 0.001091    time: 0.6196  last_time: 0.6138  data_time: 0.0023  last_data_time: 0.0017   lr: 0.00019811  max_mem: 19774M
[12/16 17:11:40 d2.utils.events]:  eta: 12:53:50  iter: 4979  total_loss: 0.001044    time: 0.6196  last_time: 0.6183  data_time: 0.0032  last_data_time: 0.0018   lr: 0.00019809  max_mem: 19774M
[12/16 17:11:53 fvcore.common.checkpoint]: Saving checkpoint to ./output/model_0004999.pth
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
[12/16 17:11:56 d2.data.datasets.coco]: Loaded 6363 images with semantic segmentation from /home/user/LISA-dataset/RS-datasets/OVS_datasets/iSAID_split/val/imgs
[12/16 17:11:56 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(640, 640), max_size=2560, sample_style='choice')]
[12/16 17:11:56 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[12/16 17:11:56 d2.data.common]: Serializing 6363 elements to byte tensors and concatenating them all ...
[12/16 17:11:56 d2.data.common]: Serialized dataset takes 1.52 MiB
[12/16 17:11:56 d2.data.datasets.coco]: Loaded 6363 images with semantic segmentation from /home/user/LISA-dataset/RS-datasets/OVS_datasets/iSAID_split/val/imgs
[12/16 17:11:56 d2.evaluation.evaluator]: Start inference on 1591 batches
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Traceback (most recent call last):
  File "/home/user/OVRS/train_net.py", line 317, in <module>
    launch(
  File "/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/detectron2/engine/launch.py", line 69, in launch
    mp.start_processes(
  File "/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/detectron2/engine/launch.py", line 123, in _distributed_worker
    main_func(*args)
  File "/home/user/OVRS/train_net.py", line 311, in main
    return trainer.train()
  File "/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/detectron2/engine/defaults.py", line 520, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/detectron2/engine/train_loop.py", line 156, in train
    self.after_step()
  File "/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/detectron2/engine/train_loop.py", line 190, in after_step
    h.after_step()
  File "/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/detectron2/engine/hooks.py", line 556, in after_step
    self._do_eval()
  File "/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/detectron2/engine/hooks.py", line 529, in _do_eval
    results = self._func()
  File "/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/detectron2/engine/defaults.py", line 489, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/detectron2/engine/defaults.py", line 653, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/detectron2/evaluation/evaluator.py", line 172, in inference_on_dataset
    evaluator.process(inputs, outputs)
  File "/home/user/anaconda3/envs/RRSIS/lib/python3.9/site-packages/detectron2/evaluation/sem_seg_evaluation.py", line 138, in process
    self._conf_matrix += np.bincount(
ValueError: cannot reshape array of size 2304 into shape (16,16)

```

**Comment by ray38080289** [comment]
@derektan95  Just modify the config num_classes and class_json to right dataset

![Image](https://github.com/user-attachments/assets/0f28f52c-783a-408c-8b34-c009e77b733f)
